const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),{createGameServer}=require('../server'),G=require('../engine'),A=require('node:assert/strict'),fs=require('fs'),path=require('path');
(async()=>{const game=createGameServer();await new Promise(r=>game.server.listen(0,r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']}),contexts=[],pages=[],errors=[],bad=[];const out=path.join(__dirname,'../qa');fs.mkdirSync(out,{recursive:true});const url=`http://127.0.0.1:${game.server.address().port}`;try{
 for(let i=0;i<6;i++){const context=await browser.newContext(i===5?{viewport:{width:844,height:390},isMobile:true,hasTouch:true,deviceScaleFactor:1}:{viewport:{width:1280,height:850}});contexts.push(context);const p=await context.newPage();pages.push(p);p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)bad.push(r.url());});await p.goto(url);await p.locator('#create').waitFor({state:'visible'});await p.waitForFunction(()=>!document.getElementById('create').disabled);await p.locator('#name').fill('Browser '+i);if(!i){await p.locator('#create').click();await p.locator('#lobby').waitFor({state:'visible'});}else{const code=await pages[0].locator('#roomCode').innerText();await p.locator('#joinBtn').click();await p.locator('#code').fill(code);await p.locator('#join').click();await p.locator('#lobby').waitFor({state:'visible'});}await p.locator('#chars button').filter({hasText:G.W.CHARS[i]}).click();}
 const host=pages[0],code=await host.locator('#roomCode').innerText(),r=game.rooms.get(code);await host.locator('#start').click();await host.locator('#play').waitFor({state:'visible'});await host.locator('#devToggle').click();
 const dev=async(action,value)=>{await host.evaluate(({action,value})=>new Promise(resolve=>socket.emit('dev',{action,value},resolve)),{action,value});await host.waitForTimeout(250);};
 await host.evaluate(()=>scrollTo(0,0));await host.screenshot({path:path.join(out,'level1.png')});
 for(let level=2;level<=5;level++){await dev('jump',level);await host.waitForTimeout(300);await host.evaluate(()=>scrollTo(0,0));await host.screenshot({path:path.join(out,`level${level}.png`)});A.equal(await host.evaluate(()=>room.stage.id),level);A.ok(await host.locator('#objective').innerText());}
 await dev('jump',2);const idx=[...r.players.values()].findIndex(p=>p.token===r.stage.readers[0]);await pages[idx].locator('#puzzleButtons button').click();await pages[idx].waitForTimeout(300);A.ok((await pages[idx].locator('#privateClue').innerText()).includes('→'));const non=pages[(idx+1)%6];A.ok(!(await non.locator('#privateClue').innerText()).includes('→'));await pages[idx].waitForTimeout(2400);A.ok(!(await pages[idx].locator('#privateClue').innerText()).includes('→'));
 await dev('jump',3);await dev('finalSlope');await host.waitForTimeout(700);await host.evaluate(()=>scrollTo(0,0));await host.screenshot({path:path.join(out,'mountain-slope.png')});
 await dev('jump',4);await dev('flatten');await host.waitForTimeout(200);A.equal(await host.evaluate(()=>own.flat),true);await dev('revive');A.equal(await host.evaluate(()=>own.flat),false);await dev('bossAll');await host.waitForTimeout(2400);A.equal(await host.evaluate(()=>room.stage.cleared),true);
 await dev('jump',5);const momo=pages[3],token=r.momoToken;await momo.reload();await momo.waitForFunction(()=>room?.started&&room.stage.id===5);A.equal(await momo.evaluate(()=>myId),token);
 await dev('finalHold');for(const p of pages)await p.evaluate(()=>actionDown('interact'));await host.waitForFunction(()=>room.stage.id==='ending');const whiteAt=Date.now();await host.locator('#whiteScreen').waitFor({state:'visible'});for(const p of pages){A.equal(await p.locator('#whiteCopy').innerText(),'');A.equal(await p.locator('#whiteScreen').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)');}await host.evaluate(()=>scrollTo(0,0));await host.screenshot({path:path.join(out,'white-blank.png')});await host.waitForTimeout(4500);A.equal(await host.locator('#whiteCopy').innerText(),'');await momo.waitForFunction(()=>document.getElementById('whiteCopy').textContent.includes('沒想法'));const whiteDuration=Date.now()-whiteAt;A.ok(whiteDuration>=4900);A.equal(await host.locator('#whiteCopy').innerText(),'系統好像漏掉了什麼。');await momo.screenshot({path:path.join(out,'white-momo.png')});await host.evaluate(()=>scrollTo(0,0));await host.screenshot({path:path.join(out,'white-friends.png')});
 await host.waitForFunction(()=>room.stage.phase==='send',{timeout:20000});for(const p of pages.filter((_,i)=>i!==3)){await p.locator('#sendStar').click();}A.equal(await momo.locator('#sendStar').isVisible(),false);await host.waitForFunction(()=>room.stage.phase==='celebrate',{timeout:10000});await host.evaluate(()=>scrollTo(0,0));await host.screenshot({path:path.join(out,'birthday.png')});await host.waitForFunction(()=>room.stage.id==='party',{timeout:15000});await host.evaluate(()=>scrollTo(0,0));await host.screenshot({path:path.join(out,'party.png')});await pages[5].evaluate(()=>scrollTo(0,0));await pages[5].screenshot({path:path.join(out,'party-mobile.png')});A.ok((await host.locator('#instructions').innerText()).includes('叫五個人陪妳闖了五關'));
 const x=await host.evaluate(()=>own.x);await host.keyboard.down('d');await host.waitForTimeout(350);await host.keyboard.up('d');A.ok(await host.evaluate(()=>own.x)>x);await host.locator('#resetGame').click();await host.locator('#confirmReset').waitFor({state:'visible'});A.equal(r.started,true);await host.locator('#confirmReset').click();await host.locator('#lobby').waitFor({state:'visible'});A.equal(r.players.size,6);
 A.deepEqual(errors,[]);A.deepEqual(bad,[]);const report={passed:true,browser:'Chromium',contexts:6,mobileViewport:'844x390 touch emulation',whiteDurationMs:whiteDuration,pageErrors:errors,httpErrors:bad,screenshots:fs.readdirSync(out).filter(x=>x.endsWith('.png'))};fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{await browser.close();await game.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
