const test=require('node:test'),assert=require('node:assert/strict');const G=require('../engine');
function setup(id=1){const p=G.player('Ollie');p.char='吉伊卡哇';const r=G.room('TEST',p);G.addBots(r);for(const b of r.players.values()){b.bot=false;b.char??='小桃';}r.dev={assist:false,follow:false};G.enter(r,id);return {r,p,ps:[...r.players.values()]};}
function advance(r,seconds){for(let i=0;i<Math.ceil(seconds/.025);i++){for(const p of r.players.values())p.lastInput=r.time;G.tick(r,.025);}}
function at(p,x,y=420){G.warp(p,x,y);}
test('six slots, unique character picks and momo identity',()=>{const p=G.player('host');p.char='吉伊卡哇';const r=G.room('ABCD',p);G.addBots(r);assert.equal(r.players.size,6);assert.equal(new Set([...r.players.values()].map(p=>p.char)).size,6);assert.equal(r.players.get(r.momoToken).char,'小桃');});
test('L1 pressure plates are spatially distinct; gate closes until far lever latches',()=>{const {r,p,ps}=setup();ps.slice(0,3).forEach(p=>at(p,650));advance(r,.1);assert.equal(r.stage.gateOpen,false);[650,770,890].forEach((x,i)=>at(ps[i],x));advance(r,.1);assert.equal(r.stage.gateOpen,true);at(ps[0],600);advance(r,.1);assert.equal(r.stage.gateOpen,false);at(ps[0],650);advance(r,.1);at(ps[3],1200);G.interact(r,ps[3]);ps.forEach(p=>at(p,1200));advance(r,.1);assert.equal(r.stage.gateOpen,true);assert.equal(r.stage.leverOn,true);});
test('L1 bridge breaks at fourth distinct crossing, not first',()=>{const {r,ps}=setup();r.stage.leverOn=true;for(let i=0;i<3;i++){at(ps[i],1450);advance(r,.025);assert.equal(r.stage.bridgeBroken,false);}at(ps[3],1450);advance(r,.025);assert.equal(r.stage.bridgeBroken,true);});
test('L1 completion requires gathered active players and preserves fragment',()=>{const {r,ps}=setup();r.stage.leverOn=true;ps.slice(0,5).forEach(p=>at(p,2730));advance(r,.1);assert.equal(r.stage.cleared,false);at(ps[5],2730);advance(r,.1);assert.equal(r.stage.cleared,true);assert.deepEqual(r.fragments,[1]);advance(r,1);G.interact(r,ps[0]);assert.equal(r.stage.id,2);assert.deepEqual(r.fragments,[1]);});
test('moving planks provide actual collision support and falling respawns in ~3 seconds',()=>{const {r,p}=setup();const b=G.W.platforms(r.stage,r.time)[0];at(p,b.x+30,b.y-3);p.vy=100;advance(r,.05);assert.equal(p.y,b.y);at(p,1600,690);r.stage.bridgeBroken=true;advance(r,.025);assert.equal(p.down,true);advance(r,2.8);assert.equal(p.down,true);advance(r,.3);assert.equal(p.down,false);assert.equal(p.x,p.checkpoint);});
test('L2 correct paired operator, wrong symbol BOING and all three two-step solutions',()=>{const {r,ps}=setup(2);r.stage.pairs.forEach((q,i)=>{const reader=ps[i*2],op=ps[i*2+1];at(reader,740+i*800);at(op,740+i*800);assert.equal(G.puzzle(r,reader,{kind:'symbol',value:q.seq[0]}).ok,false);G.puzzle(r,op,{kind:'symbol',value:99});assert.equal(q.fail,1);assert.equal(q.entered.length,0);assert.equal(op.vy,-690);q.seq.forEach(value=>G.puzzle(r,op,{kind:'symbol',value}));assert.equal(q.symbolSolved,true);G.puzzle(r,op,{kind:'color',value:'blue'});assert.equal(q.solved,false);G.puzzle(r,op,{kind:'color',value:'red'});assert.equal(q.solved,true);});ps.forEach(p=>at(p,2820));advance(r,.05);assert.equal(r.stage.cleared,true);});
test('L3 cargo responds to pushing, rolls and supports riding',()=>{const {r,p,ps}=setup(3);ps.slice(1).forEach(p=>at(p,2800));at(p,202);p.input={right:true};advance(r,1.5);assert.ok(r.stage.cargo.x>320);const c=r.stage.cargo;assert.ok(c.angle>0);at(p,c.x,c.y-c.r-2);p.vy=20;p.input={};advance(r,.025);assert.ok(p.y<350,'player stands on cargo');});
test('L3 slope rolls back without support, seesaw loses cargo and recovers',()=>{const {r,ps}=setup(3);ps.forEach(p=>at(p,2700));Object.assign(r.stage.cargo,{x:700,y:325,vx:0});advance(r,1);assert.ok(r.stage.cargo.x<690);Object.assign(r.stage.cargo,{x:1590,y:365,vx:0});ps.forEach(p=>at(p,1600));advance(r,2);assert.ok(r.stage.cargo.falling||r.stage.cargo.x<1240);advance(r,3);assert.ok(r.stage.cargo.x<1240);});
test('L3 fan needs three distinct switches; destination has mushroom then fragment',()=>{const {r,ps}=setup(3);[1760,1860,1960].forEach((x,i)=>at(ps[i],x));advance(r,.05);assert.deepEqual(r.stage.plates,[true,true,true]);ps[1].x=1760;advance(r,.05);assert.equal(r.stage.plates[1],false);r.stage.cargo.x=2820;advance(r,.05);assert.equal(r.stage.delivered,true);assert.equal(r.stage.cleared,false);advance(r,3.1);assert.equal(r.stage.cleared,true);assert.deepEqual(r.fragments,[3]);});
test('L4 holds two mechanisms, two ammo deliveries per cannon, three distinct shots and fake-out',()=>{const {r,ps}=setup(4),s=r.stage;at(ps[0],350);at(ps[1],2240);ps[0].input=ps[1].input={interact:true};advance(r,.05);for(const c of s.cannons){for(const carrier of [ps[2],ps[3]]){at(carrier,150);assert.equal(G.interact(r,carrier).ok,true);assert.equal(carrier.carry,true);at(carrier,c.x);G.interact(r,carrier);}at(ps[4],c.x);s.boss.x=c.x;s.mechs=[r.time+1,r.time+1];G.interact(r,ps[4]);assert.equal(c.fired,true);}assert.equal(s.hits,3);assert.equal(s.fake,'defeated');advance(r,2.1);assert.equal(s.fake,'phase2');advance(r,2);assert.equal(s.fake,'eating');advance(r,4);assert.equal(s.fake,'sitting');assert.equal(s.cleared,true);});
test('L4 cannot fire without two live mechanisms and nearby boss',()=>{const {r,p}=setup(4);const c=r.stage.cannons[0];c.ammo=2;at(p,c.x);r.stage.boss.x=c.x;assert.equal(G.interact(r,p).ok,false);r.stage.mechs=[r.time+1,r.time+1];r.stage.boss.x=2300;assert.equal(G.interact(r,p).ok,false);assert.equal(r.stage.hits,0);});
test('teammate rescue is held for two seconds, automatic respawn at three',()=>{const {r,ps}=setup(4);at(ps[0],100);at(ps[1],140);G.down(r,ps[0]);ps[1].input={interact:true};advance(r,1.9);assert.equal(ps[0].down,true);advance(r,.2);assert.equal(ps[0].down,false);});
test('L5 paired clue, star, four sockets, shared three-second hold and reveal ordering',()=>{const {r,ps}=setup(5);r.fragments=[1,2,3,4];[330,430,530].forEach((x,i)=>at(ps[i],x));advance(r,.05);assert.equal(r.stage.plateLatch,true);at(ps[1],1070);[3,1,0].forEach(value=>G.puzzle(r,ps[1],{kind:'tower',value}));assert.equal(r.stage.clueSolved,true);r.stage.star.x=2100;advance(r,2.2);assert.equal(r.stage.sockets,4);assert.equal(r.stage.chest,true);ps.forEach(p=>at(p,2750));ps.slice(0,5).forEach(p=>p.input={interact:true});advance(r,1);assert.equal(r.stage.hold,0);ps[5].input={interact:true};advance(r,2.8);assert.equal(r.stage.id,5);advance(r,1);assert.equal(r.stage.id,'ending');assert.equal(r.stage.phase,'complete');advance(r,2.1);assert.equal(r.stage.phase,'missing');});
test('ending target cannot send, five independent idempotent stars, party unlock',()=>{const {r,ps}=setup();G.enter(r,'ending');const momo=r.players.get(r.momoToken);assert.ok(momo);advance(r,11.1);assert.equal(r.stage.phase,'send');assert.equal(G.sendStar(r,momo.token).ok,false);const senders=ps.filter(p=>p!==momo);for(const p of senders){assert.equal(G.sendStar(r,p.token).ok,true);assert.equal(G.sendStar(r,p.token).ok,false);}assert.equal(r.stage.stars.length,5);advance(r,1.3);assert.equal(r.stage.sent.length,5);advance(r,9.2);assert.equal(r.stage.id,'party');const x=ps[0].x;ps[0].input={right:true};advance(r,.5);assert.ok(ps[0].x>x);});
test('offline momo identity persists through L5 and ending without replacing the target',()=>{const {r}=setup(5);const target=r.momoToken;r.players.get(target).connected=false;G.enter(r,'ending');assert.equal(r.stage.target,target);assert.equal(r.stage.stars.length,5);r.players.get(target).connected=true;assert.equal(r.stage.target,target);});
test('DEV authorization, jumps, fragments, bots, momo and deterministic pair assistance',()=>{const {r,p,ps}=setup();assert.equal(G.dev(r,ps[1],{action:'jump',value:5}).ok,false);for(let i=1;i<=5;i++){assert.equal(G.dev(r,p,{action:'jump',value:i}).ok,true);assert.equal(r.stage.id,i);}G.dev(r,p,{action:'fragments'});assert.deepEqual(r.fragments,[1,2,3,4]);G.dev(r,p,{action:'pair'});assert.equal(r.stage.clueSolved,true);G.dev(r,p,{action:'ending'});assert.equal(r.stage.id,'ending');});
module.exports={setup,advance,at};
