const test=require('node:test'),assert=require('node:assert/strict');const G=require('../engine');
function setup(id=1){const p=G.player('Ollie');p.char='吉伊卡哇';const r=G.room('TEST',p);G.addBots(r);for(const b of r.players.values()){b.bot=false;b.char??='小桃';}r.dev={assist:false,follow:false};G.enter(r,id);return {r,p,ps:[...r.players.values()]};}
function advance(r,seconds){for(let i=0;i<Math.ceil(seconds/.025);i++){for(const p of r.players.values())p.lastInput=r.time;G.tick(r,.025);}}
function at(p,x,y=420){G.warp(p,x,y);}
test('six slots, unique character picks and momo identity',()=>{const p=G.player('host');p.char='吉伊卡哇';const r=G.room('ABCD',p);G.addBots(r);assert.equal(r.players.size,6);assert.equal(new Set([...r.players.values()].map(p=>p.char)).size,6);assert.equal(r.players.get(r.momoToken).char,'小桃');});
test('L1 pressure plates are spatially distinct; gate closes until far lever latches',()=>{const {r,p,ps}=setup();ps.slice(0,3).forEach(p=>at(p,650));advance(r,.1);assert.equal(r.stage.gateOpen,false);[650,770,890].forEach((x,i)=>at(ps[i],x));advance(r,.1);assert.equal(r.stage.gateOpen,true);at(ps[0],600);advance(r,.1);assert.equal(r.stage.gateOpen,false);at(ps[0],650);advance(r,.1);at(ps[3],1200);G.interact(r,ps[3]);ps.forEach(p=>at(p,1200));advance(r,.1);assert.equal(r.stage.gateOpen,true);assert.equal(r.stage.leverOn,true);});
test('L1 bridge breaks at fourth distinct crossing, not first',()=>{const {r,ps}=setup();r.stage.leverOn=true;for(let i=0;i<3;i++){at(ps[i],1450);advance(r,.025);assert.equal(r.stage.bridgeBroken,false);}at(ps[3],1450);advance(r,.025);assert.equal(r.stage.bridgeBroken,true);});
test('L1 completion requires gathered active players and preserves fragment',()=>{const {r,ps}=setup();r.stage.leverOn=true;ps.slice(0,5).forEach(p=>at(p,2730));advance(r,.1);assert.equal(r.stage.cleared,false);at(ps[5],2730);advance(r,.1);assert.equal(r.stage.cleared,true);assert.deepEqual(r.fragments,[1]);advance(r,1);G.interact(r,ps[0]);assert.equal(r.stage.id,2);assert.deepEqual(r.fragments,[1]);});
test('moving planks provide actual collision support and falling respawns in ~3 seconds',()=>{const {r,p}=setup();const b=G.W.platforms(r.stage,r.time)[0];at(p,b.x+30,b.y-3);p.vy=100;advance(r,.05);assert.equal(p.y,b.y);at(p,1600,690);r.stage.bridgeBroken=true;advance(r,.025);assert.equal(p.down,true);advance(r,2.8);assert.equal(p.down,true);advance(r,.3);assert.equal(p.down,false);assert.equal(p.x,p.checkpoint);});
