const test=require('node:test'),A=require('node:assert/strict'),G=require('../engine'),L=G.L,D=G.W.D;
function setup(id){const p=G.player('host');p.char='吉伊卡哇';const r=G.room('TEST',p);G.addBots(r);for(const p of r.players.values())p.bot=false;r.dev={assist:false,follow:false};G.enter(r,id);return {r,p,ps:[...r.players.values()]};}
function advance(r,n){for(let i=0;i<Math.ceil(n/.025);i++){for(const p of r.players.values())p.lastInput=r.time;G.tick(r,.025);}}
const at=(p,x,y=420)=>G.warp(p,x,y);
function relay(r){const s=r.stage,p=r.players.get(s.executors[s.leg]),answer=s._legs[s.leg].truth.slice();at(r.players.get(s.readers[0]),D.caves[s.cave-1].readers[0]);A.equal(G.interact(r,r.players.get(s.readers[0])).ok,true);advance(r,s.cfg.display+.025);for(const v of answer){at(p,D.caves[s.cave-1].pads[v]);G.interact(r,p);advance(r,.025);}}
test('jump reaches 160–180px; all L2 gates block air movement',()=>{const {r,p}=setup(1);at(p,100);p.input={jump:true};let y=420;for(let i=0;i<30;i++){advance(r,.025);y=Math.min(y,p.y);}A.ok(420-y>160&&420-y<180);G.enter(r,2);for(let c=1;c<=5;c++){G.dev(r,p,{action:'cave',value:c});at(p,D.caves[c-1].gate-35);p.input={right:true,jump:true};advance(r,.5);A.ok(p.x<=D.caves[c-1].gate-23);}});
test('L2 every leg manual / distinct executors / reader excluded',()=>{const {r}=setup(2),s=r.stage;A.equal(new Set(s.executors).size,4);A.ok(!s.executors.some(t=>s.readers.includes(t)));advance(r,12);A.equal(s.mode,'waiting');A.equal(G.puzzle(r,r.players.get(s.executors[0]),{kind:'startLeg'}).ok,false);relay(r);A.equal(s.leg,1);advance(r,8);A.equal(s.mode,'waiting');});
test('L2 private timed display, discussion has no countdown, first physical input starts timer, timeout preserves prior caves',()=>{const {r,p}=setup(2);G.dev(r,p,{action:'cave',value:3});const s=r.stage,reader=r.players.get(s.readers[0]),op=r.players.get(s.executors[0]);at(reader,D.caves[s.cave-1].readers[0]);G.interact(r,reader);A.equal(L.privateClue(r,reader).sequence.length,5);A.equal(L.privateClue(r,op).sequence,null);advance(r,2);A.equal(L.privateClue(r,reader).sequence,null);advance(r,20);A.equal(s.inputUntil,null);at(op,D.caves[2].pads[s._legs[0].truth[0]]);G.interact(r,op);advance(r,.025);A.equal(s.mode,'input');const round=s.round;advance(r,5.1);A.equal(s.round,round+1);A.equal(s.cave,3);A.deepEqual(s.caveCleared.slice(1,3),[true,true]);});
test('L2 5,000 generated true/fake pairs validate exactly one, differ by <=2; simultaneous reader starts lock',()=>{for(const rule of L.rules)for(let i=0;i<1000;i++){const [a,b]=L.answerPair(8,rule);A.equal(rule.valid(a),true);A.equal(rule.valid(b),false);A.ok(a.filter((x,i)=>x!==b[i]).length<=2);}const {r,p}=setup(2);for(const cave of [4,5]){G.dev(r,p,{action:'cave',value:cave});const s=r.stage;A.equal(s.readers.length,2);at(r.players.get(s.readers[0]),D.caves[s.cave-1].readers[0]);A.equal(G.interact(r,r.players.get(s.readers[0])).ok,true);const until=s.displayUntil;A.equal(G.interact(r,r.players.get(s.readers[1])).ok,false);A.equal(s.displayUntil,until);}});
test('L2 all 20 physical-input legs and six-player exit; wrong input restarts cave only',()=>{const {r,ps}=setup(2);for(let c=1;c<=5;c++)for(let j=0;j<4;j++){A.equal(r.stage.cave,c);relay(r);}A.equal(r.stage.mode,'complete');ps.forEach(p=>at(p,5100));ps[5].connected=false;advance(r,.1);A.equal(r.stage.cleared,false);ps[5].connected=true;advance(r,.1);A.equal(r.stage.cleared,true);G.enter(r,2);G.dev(r,ps[0],{action:'cave',value:4});const s=r.stage,op=r.players.get(s.executors[0]);at(r.players.get(s.readers[0]),D.caves[s.cave-1].readers[0]);G.interact(r,r.players.get(s.readers[0]));advance(r,3);at(op,D.caves[3].pads[(s._legs[0].truth[0]+1)%4]);G.interact(r,op);advance(r,.025);A.equal(s.failures,1);A.ok(s.caveCleared.slice(1,4).every(Boolean));});
test('L3 1..6 push profile: 3 normal, 4+ dangerous',()=>{const speeds=[];for(let n=1;n<=6;n++){const {r,p}=setup(3);G.dev(r,p,{action:'pushers',value:n});advance(r,1);speeds.push(r.stage.cargo.vx);}A.ok(speeds[0]<speeds[1]&&speeds[1]<speeds[2]);A.ok(speeds[2]<80&&speeds[3]>125&&speeds[5]>260);});
test('L3 route mechanisms require physical E; major pit resets route',()=>{const {r,ps}=setup(3),s=r.stage;const k=D.cargo.switches[0];at(ps[0],k.x,k.y);advance(r,.05);A.equal(s.obstacles[0],false);A.equal(G.interact(r,ps[0]).ok,true);A.equal(s.obstacles[0],true);s.cargo.x=3820;s.cargo.vx=200;advance(r,2);A.ok(s.cargo.x<300);A.deepEqual(s.obstacles,[false,false,false]);s.cargoCheckpoint=2500;s.obstacles=[true,true,false];s.switches={bridge:true,gateA:true,gateB:true};s.cargo.x=3820;s.cargo.vx=200;advance(r,2);A.equal(s.cargo.x,2500);A.deepEqual(s.obstacles,[true,true,false]);A.equal(ps[0].checkpoint,2500);});
test('L3 final slope reverses staffing and rollback resets to checkpoint only',()=>{for(const [n,direction]of [[6,1],[5,1],[4,-1]]){const {r,p}=setup(3);G.dev(r,p,{action:'finalSlope'});G.dev(r,p,{action:'pushers',value:n});r.stage.cargo.x=4300;advance(r,1);A.equal(Math.sign(r.stage.cargo.x-4300),direction);}const {r,p}=setup(3);G.dev(r,p,{action:'finalSlope'});G.dev(r,p,{action:'pushers',value:0});advance(r,2);A.ok(r.stage.cargo.x>=4160);A.ok(r.stage.obstacles.every(Boolean));});
test('L3 cargo supports rider; summit mushroom then fragment',()=>{const {r,p}=setup(3),c=r.stage.cargo;at(p,c.x,c.y-c.r-2);p.vy=25;advance(r,.05);A.ok(p.y<=c.y-c.r+2);c.x=5390;c.y=D.mountain(c.x)-55;r.stage.obstacles=[true,true,true];advance(r,.05);A.equal(r.stage.delivered,true);advance(r,3.1);A.equal(r.stage.cleared,true);});
test('L4 direct jump and airborne underpass physically feasible across timing margins',()=>{for(const under of [false,true])for(const offset of [-12,0,12]){const {r,p}=setup(4);L.beginBoss(r,under?'leap':'recovery',1);if(!under)r.stage.boss.next='crouch';at(p,1880+offset);p.input={right:true,jump:!under};advance(r,1.2);A.ok(p.x>2100);A.equal(p.flat,false,`${under?'underpass':'jump'} offset ${offset}`);}});
test('L4 flattened slow movement/no automatic revive/0.5s rescue/0.5s protection',()=>{const {r,ps}=setup(4);at(ps[0],900);at(ps[1],950);L.flatten(r,ps[0],G);ps[0].input={right:true};advance(r,.5);A.ok(ps[0].x>900&&ps[0].x<920);ps[0].input={};advance(r,4);A.equal(ps[0].flat,true);ps[1].input={interact:true};advance(r,.475);A.equal(ps[0].flat,true);advance(r,.05);A.equal(ps[0].flat,false);A.ok(ps[0].invulnerableUntil>r.time);L.flatten(r,ps[0],G);A.equal(ps[0].flat,false);advance(r,.55);L.flatten(r,ps[0],G);A.equal(ps[0].flat,true);});
test('L4 per-person completion persists through hit; 6/6 bridge opens; falling player respawns far end',()=>{const {r,ps}=setup(4);for(const [i,p] of ps.entries()){at(p,D.boss.buttons[i]);A.equal(G.interact(r,p).ok,true);}at(ps[0],2000);L.flatten(r,ps[0],G);advance(r,.1);A.equal(r.stage.completed.length,6);A.equal(r.stage.bridgeOpen,true);advance(r,2.6);A.equal(ps[0].down,false);A.ok(ps[0].x>3500);A.equal(r.stage.cleared,true);});
test('L5 cliff death restores personal checkpoint only',()=>{const {r,ps}=setup(5);at(ps[0],3000);advance(r,.1);A.equal(ps[0].checkpoint,2950);at(ps[1],4500,350);advance(r,.1);const x=ps[1].x;at(ps[0],3400,690);advance(r,.025);A.equal(ps[0].down,true);advance(r,.7);A.equal(ps[0].x,2950);A.equal(ps[1].x,x);});
test('L5 flatten >3 seconds dies, rescue prevents death',()=>{const {r,ps}=setup(5);at(ps[0],900);at(ps[1],950);L.flatten(r,ps[0],G);advance(r,2.9);A.equal(ps[0].down,false);advance(r,.15);A.equal(ps[0].down,true);advance(r,.7);A.equal(ps[0].x,120);at(ps[0],900);advance(r,.55);L.flatten(r,ps[0],G);ps[1].input={interact:true};advance(r,.55);A.equal(ps[0].flat,false);A.equal(ps[0].x,900);});
test('L5 final hold needs all six alive/connected, releases reset; transitions directly white',()=>{const {r,ps}=setup(5);ps.forEach(p=>{at(p,5500,350);p.input={interact:true};});ps[5].connected=false;advance(r,1);A.equal(r.stage.hold,0);ps[5].connected=true;advance(r,2);A.equal(r.stage.id,5);ps[5].input={};advance(r,.025);A.equal(r.stage.hold,0);ps[5].input={interact:true};advance(r,3.1);A.equal(r.stage.id,'ending');A.equal(r.stage.phase,'white');});
test('ending five-second blank and personalized text; five idempotent senders; persistent party',()=>{const {r,ps}=setup(1);G.enter(r,'ending');advance(r,4.975);A.equal(r.stage.phase,'white');A.equal(L.privateClue(r,ps[0]),null);advance(r,.05);A.equal(r.stage.phase,'whiteText');for(const p of ps)A.equal(L.privateClue(r,p).text,p.token===r.momoToken?'啊……製作人做不下去了。\n沒想法了。':'系統好像漏掉了什麼。');advance(r,11.6);A.equal(r.stage.phase,'send');A.equal(G.sendStar(r,r.momoToken).ok,false);for(const p of ps.filter(p=>p.token!==r.momoToken)){A.equal(G.sendStar(r,p.token).ok,true);A.equal(G.sendStar(r,p.token).ok,false);}advance(r,1.3);A.equal(r.stage.sent.length,5);advance(r,9.2);A.equal(r.stage.id,'party');advance(r,60);A.equal(r.stage.id,'party');});
test('Reset current preserves previous fragments; RESET GAME clears run, keeps identities/momo/room',()=>{const {r,p,ps}=setup(4),tokens=ps.map(p=>p.token),momo=r.momoToken;r.fragments=[1,2,3,4];r.stage.completed=tokens.slice();A.equal(G.resetLevel(r,ps[1]).ok,false);G.resetLevel(r,p);A.deepEqual(r.fragments,[1,2,3]);A.deepEqual(r.stage.completed,[]);G.resetGame(r,p);A.equal(r.started,false);A.deepEqual([...r.players.keys()],tokens);A.equal(r.momoToken,momo);A.deepEqual(r.fragments,[]);for(let id=1;id<=5;id++){G.enter(r,id);const previous=Array.from({length:id-1},(_,i)=>i+1);r.fragments=previous.concat(id);ps.forEach(q=>{q.flat=true;q.down=true;});A.equal(G.resetLevel(r,p).ok,true);A.equal(r.stage.id,id);A.deepEqual(r.fragments,previous);A.ok(ps.every(q=>!q.flat&&!q.down&&q.checkpoint===120));if(id===2)A.equal(r.stage.mode,'waiting');if(id===3)A.equal(r.stage.cargo.x,280);if(id===4)A.equal(r.stage.completed.length,0);if(id===5)A.equal(r.stage.hold,0);}});
test('DEV level actions host-only',()=>{const {r,p,ps}=setup(1);for(let i=1;i<=5;i++){A.equal(G.dev(r,ps[1],{action:'jump',value:i}).ok,false);A.equal(G.dev(r,p,{action:'jump',value:i}).ok,true);}for(const action of ['finalHold','flatten','death'])A.equal(G.dev(r,p,{action}).ok,true);G.dev(r,p,{action:'jump',value:2});A.equal(G.dev(r,p,{action:'relayInspect'}).inspect.uniqueExecutors,true);});
test('L5 every gap and moving/falling platform has a physical jump path at multiple phases',()=>{for(const initialTime of [0,1.7,3.4,5.1])for(const [a,b]of D.gaps){const {r,p}=setup(5);r.time=initialTime;at(p,a-10,G.W.floor(r.stage,a-10));const bridge=G.W.platforms(r.stage,r.time).find(q=>q.x+q.w>a&&q.x<b),targets=bridge?[bridge.id,'exit']:['exit'];for(const target of targets){let landed=false,jumped=false;for(let n=0;n<180;n++){const q=target==='exit'?null:G.W.platforms(r.stage,r.time).find(q=>q.id===target),x=q?q.x+q.w/2:b+12;const dx=x-p.x,input={left:dx<-5,right:dx>5,jump:!jumped};G.W.step(p,input,r.stage,.025,r.time);jumped=true;r.time+=.025;if(n>4&&p.grounded&&Math.abs(p.x-x)<30){landed=true;break;}if(p.y>680)break;}A.ok(landed,`gap ${a}-${b}, phase ${initialTime}, target ${target}, position ${p.x},${p.y}`);p.jumpHeld=false;}}});
test('L2 generated answers fit estimated physical traversal budget',()=>{const {r,p}=setup(2);for(let c=1;c<=5;c++)for(let i=0;i<100;i++){G.dev(r,p,{action:'cave',value:c});for(const l of r.stage._legs)A.ok(L.inputCost(l.truth)<=r.stage.cfg.limit-.4);}});

test('all six flattened can slowly regroup and rescue each other without restarting L4',()=>{const {r,ps}=setup(4);ps.forEach((p,i)=>{at(p,900+i*10);L.flatten(r,p,G);p.input={interact:true};});advance(r,.55);A.ok(ps.every(p=>!p.flat&&!p.down));A.equal(r.stage.id,4);A.equal(r.stage.epoch,1);});
