const test=require('node:test'),A=require('node:assert/strict'),{io}=require('socket.io-client'),{createGameServer}=require('../server'),G=require('../engine');
const wait=ms=>new Promise(r=>setTimeout(r,ms)),emit=(s,e,d={})=>new Promise((resolve,reject)=>s.timeout(3000).emit(e,d,(err,v)=>err?reject(err):resolve(v)));
async function connect(url){const s=io(url,{transports:['websocket'],forceNew:true,reconnection:false});await new Promise((r,j)=>{s.once('connect',r);s.once('connect_error',j);});return s;}
test('six real sockets: capacity, uniqueness, private relay lock, six-level reconnect, host transfer, reset confirmation, rate budget',async()=>{const game=createGameServer();await new Promise(r=>game.server.listen(0,r));const url=`http://127.0.0.1:${game.server.address().port}`,clients=[],ids=[],packets=[];try{
 for(let i=0;i<6;i++){clients[i]=await connect(url);packets[i]={};clients[i].on('room',v=>packets[i].room=v);clients[i].on('stage',v=>packets[i].stage=v.stage);clients[i].on('clue',v=>packets[i].clue=v);ids[i]=await emit(clients[i],i?'join':'create',i?{code:ids[0].code,name:'P'+i}:{name:'Host'});A.equal(ids[i].ok,true);A.equal((await emit(clients[i],'char',G.W.CHARS[i])).ok,true);}
 const r=game.rooms.get(ids[0].code),target=r.momoToken;A.equal((await emit(clients[1],'char','小桃')).ok,false);const seventh=await connect(url);A.equal((await emit(seventh,'join',{code:r.code})).ok,false);seventh.disconnect();A.equal((await emit(clients[1],'start')).ok,false);A.equal((await emit(clients[0],'start')).ok,true);A.equal((await emit(clients[1],'dev',{action:'jump',value:2})).ok,false);A.ok(!JSON.stringify(packets[0].room).includes(ids[1].playerToken));
 await emit(clients[0],'dev',{action:'jump',value:2});await emit(clients[0],'dev',{action:'cave',value:4});const si=r.stage.readers.map(t=>ids.findIndex(x=>x.id===t));const locks=await Promise.all(si.map(i=>emit(clients[i],'puzzle',{kind:'startLeg'})));A.equal(locks.filter(x=>x.ok).length,1);await wait(230);for(let i=0;i<6;i++){A.equal(!!packets[i].clue.sequence,si.includes(i));A.ok(!('_legs' in packets[i].room.stage));A.ok(!('_legs' in (packets[i].stage||{})));}
 const rejoin=async i=>{const epoch=r.stage.epoch;clients[i].disconnect();await wait(35);const s=await connect(url);clients[i]=s;const j=await emit(s,'join',{code:r.code,playerToken:ids[i].playerToken});A.equal(j.id,ids[i].id);A.equal(r.stage.epoch,epoch);A.equal(r.momoToken,target);return s;};
 const answers=JSON.stringify(r.stage._legs);await rejoin(3);A.equal(JSON.stringify(r.stage._legs),answers);
 for(const level of [3,4,5]){await emit(clients[0],'dev',{action:'jump',value:level});const p=r.players.get(ids[3].id);if(level===3){r.stage.cargo.x=4250;r.stage.finalCheckpoint=true;r.stage.obstacles=[true,true,true];}if(level===4){r.stage.completed=[p.token];G.L.flatten(r,p,G);}if(level===5){p.checkpoint=2950;G.L.flatten(r,p,G);}await rejoin(3);if(level===3)A.equal(r.stage.finalCheckpoint,true);if(level===4){A.ok(r.stage.completed.includes(p.token));A.equal(p.flat,true);}if(level===5)A.equal(p.checkpoint,2950);}
 await emit(clients[0],'dev',{action:'ending'});r.stage.at=r.time-5.1;await wait(240);let text;clients[3].on('clue',v=>text=v);await rejoin(3);clients[3].on('clue',v=>text=v);await wait(230);A.equal(r.stage.target,target);A.equal(G.L.privateClue(r,r.players.get(target)).text,'啊……製作人做不下去了。\n沒想法了。');
 let frames=0,stages=0,clues=0;clients[0].on('frame',()=>frames++);clients[0].on('stage',()=>stages++);clients[0].on('clue',()=>clues++);await wait(1100);A.ok(frames>=15&&frames<=24);A.ok(stages>=4&&stages<=7);A.ok(clues<=2);
 A.equal((await emit(clients[1],'resetGame')).ok,false);const challenge=await emit(clients[0],'resetGame');A.equal(r.started,true);A.equal((await emit(clients[0],'resetGame',{confirmation:'wrong'})).ok,false);const second=await emit(clients[0],'resetGame');A.equal((await emit(clients[0],'resetGame',{confirmation:second.confirmation})).ok,true);A.equal(r.started,false);A.equal(r.players.size,6);A.equal(r.momoToken,target);A.equal((await emit(clients[0],'resetGame',{confirmation:second.confirmation})).ok,false);
 clients[0].disconnect();await wait(80);A.equal(r.hostToken,ids[1].id);A.equal((await emit(clients[1],'dev',{action:'jump',value:5})).ok,true);
 }finally{clients.forEach(s=>s.disconnect());await game.close();}});
test('disk restart restores relay answers/roles, personal life states, credentials and momo',async()=>{const fs=require('fs'),os=require('os'),path=require('path'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'star041-')),savePath=path.join(dir,'rooms.json');let game=createGameServer({savePath}),s;try{await new Promise(r=>game.server.listen(0,r));s=await connect(`http://127.0.0.1:${game.server.address().port}`);const id=await emit(s,'create');await emit(s,'char','小桃');await emit(s,'dev',{action:'bots'});await emit(s,'dev',{action:'jump',value:2});await emit(s,'dev',{action:'follow',value:false});const r=game.rooms.get(id.code),legs=JSON.stringify(r.stage._legs);r.players.get(id.id).checkpoint=333;r.fragments=[1];game.save();s.disconnect();await game.close();game=createGameServer({savePath});await new Promise(r=>game.server.listen(0,r));s=await connect(`http://127.0.0.1:${game.server.address().port}`);const j=await emit(s,'join',{code:id.code,playerToken:id.playerToken});A.equal(j.id,id.id);const restored=game.rooms.get(id.code);A.equal(restored.momoToken,id.id);A.equal(restored.players.get(id.id).checkpoint,333);A.equal(JSON.stringify(restored.stage._legs),legs);A.deepEqual(restored.fragments,[1]);}finally{s?.disconnect();await game.close();fs.rmSync(dir,{recursive:true,force:true});}});
test('legacy 0.4 level saves migrate current level while preserving room identity and fragments',async()=>{const fs=require('fs'),os=require('os'),path=require('path'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'star-legacy-')),savePath=path.join(dir,'rooms.json'),saved=[];for(let id=2;id<=5;id++){const p=G.player('legacy');p.char='小桃';p.resumeKey='legacy-'+id;const r=G.room('OLD'+id,p);r.momoToken=p.token;G.addBots(r);r.started=true;r.fragments=[1];r.stage={id,epoch:10,at:0};saved.push({...r,players:[...r.players.values()]});}fs.writeFileSync(savePath,JSON.stringify(saved));const game=createGameServer({savePath});try{await new Promise(r=>game.server.listen(0,r));for(let id=2;id<=5;id++){const r=game.rooms.get('OLD'+id);A.equal(r.stage.id,id);A.equal(r.players.size,6);A.equal(r.players.get(r.momoToken).resumeKey,'legacy-'+id);A.deepEqual(r.fragments,[1]);A.equal(r.stage.participants.length,6);}}finally{await game.close();fs.rmSync(dir,{recursive:true,force:true});}});
