const test=require('node:test'),A=require('node:assert/strict'),G=require('../engine'),L=G.L,D=G.W.D;
function setup(id){const p=G.player('host');p.char='小桃';const r=G.room('QA',p);r.momoToken=p.token;G.addBots(r);for(const q of r.players.values())q.bot=false;r.dev={assist:false,follow:false};G.enter(r,id);return {r,p,ps:[...r.players.values()]};}
const at=(p,x,y=420)=>G.warp(p,x,y);
function advance(r,sec){for(let i=0;i<Math.ceil(sec/.025);i++){for(const p of r.players.values())p.lastInput=r.time;G.tick(r,.025);}}
function read(r){const s=r.stage,p=r.players.get(s.readers[0]);at(p,D.caves[s.cave-1].readers[0]);A.equal(G.interact(r,p).ok,true);advance(r,s.cfg.display+.025);}
function solve(r){const s=r.stage;read(r);const p=r.players.get(s.executors[s.leg]),a=s._legs[s.leg].truth.slice();for(const n of a){at(p,D.caves[s.cave-1].pads[n]);A.equal(G.interact(r,p).ok,true);advance(r,.2);}}
test('L2 physical stone authorization, no passive input, repeat symbol E and single read',()=>{const {r}=setup(2),s=r.stage,reader=r.players.get(s.readers[0]),op=r.players.get(s.executors[0]);at(op,D.caves[0].readers[0]);A.equal(G.interact(r,op).ok,false);at(reader,100);A.equal(G.interact(r,reader).ok,false);s._legs[0].truth=[2,2,2,2];read(r);for(const x of D.caves[0].pads){at(op,x);advance(r,.1);op.input={jump:true};advance(r,.3);}A.equal(s.entered.length,0);A.equal(s.inputUntil,null);A.equal(G.interact(r,reader).ok,false);A.equal(L.privateClue(r,reader).sequence,null);at(op,D.caves[0].pads[2]);for(let i=0;i<4;i++){A.equal(G.interact(r,op).ok,true);advance(r,.2);}A.equal(s.leg,1);});
test('L2 dual stones private simultaneous time window, truth independently drawn per leg',()=>{const {r,p}=setup(2);let mixed=false;for(let n=0;n<30;n++){G.dev(r,p,{action:'cave',value:5});const s=r.stage;mixed ||=new Set(s._legs.map(l=>l.reader)).size>1;const a=r.players.get(s.readers[0]),b=r.players.get(s.readers[1]);at(a,D.caves[4].readers[1]);A.equal(G.interact(r,a).ok,false);at(b,D.caves[4].readers[1]);A.equal(G.interact(r,b).ok,true);const ca=L.privateClue(r,a),cb=L.privateClue(r,b);A.equal(ca.until,cb.until);A.equal(ca.readAt,cb.readAt);A.notDeepEqual(ca.sequence,cb.sequence);A.equal([ca,cb].filter(c=>L.rules[s.ruleIndex].valid(c.sequence)).length,1);A.equal(G.interact(r,b).ok,false);}A.ok(mixed);});
test('L3 release rolls uphill cargo down; downhill accelerates without pushers',()=>{const {r}=setup(3),s=r.stage;s.obstacles=[true,true,true];s.cargo.x=620;s.cargo.y=D.mountain(620)-55;advance(r,1);A.ok(s.cargo.x<600);A.ok(s.cargo.vx<-50);s.cargo.x=2820;s.cargo.vx=0;s.cargo.y=D.mountain(2820)-55;advance(r,1);A.ok(s.cargo.x>2860);A.ok(s.cargo.vx>85);});
test('L3 three actual player inputs move cargo; rider, mechanisms and slopes remain shared geometry',()=>{const {r,ps}=setup(3),c=r.stage.cargo;for(const [i,p]of ps.slice(0,3).entries()){at(p,c.x-80-i*10);p.input={right:true};}advance(r,3);A.equal(r.stage.pushers,3);A.ok(c.x>440&&c.vx>55&&c.vx<90);});
test('L3 flatten slow/rescue/auto recovery and protection; individual nearest checkpoint fall',()=>{const {r,ps}=setup(3);at(ps[0],2500,225);advance(r,.1);A.equal(ps[0].checkpoint,2500);at(ps[0],3800,690);advance(r,.8);A.equal(ps[0].x,2500);at(ps[0],900,335);at(ps[1],950,335);advance(r,.6);L.flatten(r,ps[0],G);ps[0].input={right:true};advance(r,.4);A.ok(ps[0].x>900&&ps[0].x<915);ps[0].input={};advance(r,2.7);A.equal(ps[0].flat,false);L.flatten(r,ps[0],G);A.equal(ps[0].flat,false);advance(r,.55);L.flatten(r,ps[0],G);ps[1].input={interact:true};advance(r,.55);A.equal(ps[0].flat,false);});
test('L3 route platform jumps are physically reachable at four animation phases',()=>{for(const phase of [0,1.7,3.4,5.1])for(const [from,to]of [['ground','approach'],['approach','bridge-detour'],['bridge-detour','bridge-switch'],['hill','gate-step'],['gate-step','gate-a'],['gate-a','gate-moving'],['gate-moving','gate-b'],['flat','brake-step'],['brake-step','brake-switch'],['gap','catch-detour']]){const {r,p}=setup(3);r.time=phase;const plats=D.cargoPlatforms(r.time),src=plats.find(b=>b.id===from),dest=plats.find(b=>b.id===to);const sx=src?src.x+src.w-18:({ground:1080,hill:1810,flat:3370,gap:3710}[from]);at(p,sx,src?src.y:D.mountain(sx));let landed=false;for(let i=0;i<80;i++){const d=D.cargoPlatforms(r.time).find(b=>b.id===to),x=d.x+30,dx=x-p.x;G.W.step(p,{right:dx>4,left:dx<-4,jump:i===0},r.stage,.025,r.time);r.time+=.025;if(i>4&&p.grounded&&p.x>=d.x-10&&p.x<=d.x+d.w+10&&Math.abs(p.y-d.y)<2){landed=true;break;}if(p.y>680)break;}A.ok(landed,`${from} → ${to}, phase ${phase}, ${p.x},${p.y}`);}});
test('L4 FSM bounded continuous movement, locked charge direction, telegraphs and recovery',()=>{const {r,ps}=setup(4);ps.forEach(p=>at(p,100));const states=new Set();let prev={...r.stage.boss},chargeDir;for(let i=0;i<1800;i++){advance(r,.025);const b=r.stage.boss;states.add(b.mode);A.ok(Math.abs(b.x-prev.x)<=11);A.ok(Math.abs(b.y-prev.y)<=22);A.ok(b.x>=D.boss.bounds[0]&&b.x<=D.boss.bounds[1]);if(b.mode==='charge'){if(prev.mode!=='charge')chargeDir=b.dir;A.equal(b.dir,chargeDir);}if(b.mode==='chargeWarning')A.equal(+(b.until-b.start).toFixed(2),.55);if(b.mode==='recovery')A.ok(b.until-b.start>=.7);prev={...b};}for(const mode of ['chargeWarning','charge','recovery','crouch','leap','slam'])A.ok(states.has(mode),mode);});
test('L4 personal buttons reject passive arrival and wrong owner; return hit keeps completion',()=>{const {r,ps}=setup(4);at(ps[0],D.boss.buttons[1]);advance(r,.05);A.equal(r.stage.completed.length,0);A.equal(G.interact(r,ps[0]).ok,false);at(ps[0],D.boss.buttons[0]);A.equal(G.interact(r,ps[0]).ok,true);at(ps[0],r.stage.boss.x);advance(r,.025);A.ok(ps[0].flat);A.deepEqual(r.stage.completed,[ps[0].token]);});
test('L5 archetypes stay distinct, patrol pauses edges, hopper fixed arc and charger locks direction',()=>{const {r,ps}=setup(5);ps.forEach(p=>at(p,100));const [patrol,hopper,charger]=r.stage.enemies,types=r.stage.enemies.map(m=>m.type),seen=new Set();let prev={...patrol},lastJump,periods=[];for(let i=0;i<1000;i++){const oldMode=hopper.mode;advance(r,.025);A.deepEqual(r.stage.enemies.map(m=>m.type),types);A.ok(patrol.x>=patrol.min&&patrol.x<=patrol.max);A.ok(Math.abs(patrol.x-prev.x)<=1.31);if(patrol.mode==='turn'&&prev.mode==='turn')A.equal(patrol.x,prev.x);seen.add(patrol.mode);if(hopper.mode==='jump'&&oldMode!=='jump'){if(lastJump)periods.push(r.time-lastJump);lastJump=r.time;}A.equal(hopper.x,3100);A.ok(hopper.y>=325&&hopper.y<=420);prev={...patrol};}A.ok(seen.has('turn'));A.ok(periods.every(n=>n>2&&n<2.15));at(ps[0],charger.x-140,350);advance(r,.025);A.equal(charger.mode,'warning');const dir=charger.dir;at(ps[0],charger.x+160,350);advance(r,.475);A.equal(charger.mode,'charge');A.equal(charger.dir,dir);advance(r,.55);A.equal(charger.mode,'recovery');A.ok(charger.x>=charger.min&&charger.x<=charger.max);});
test('DEV new leg, downhill, checkpoint, all attack and completion controls work',()=>{const {r,p}=setup(2);for(const action of ['legStart','legComplete','relayInspect','caveFail'])A.equal(G.dev(r,p,{action}).ok,true,action);G.enter(r,3);for(const action of ['cargoCheckpoint','downhill','finalSlope','cargoReset','flatten','revive'])A.equal(G.dev(r,p,{action}).ok,true,action);for(let value=1;value<=6;value++)A.equal(G.dev(r,p,{action:'pushers',value}).ok,true);G.enter(r,4);for(const value of ['chargeWarning','charge','crouch','leap','slam','stompWarning','stomp','recovery']){A.equal(G.dev(r,p,{action:'bossAttack',value}).ok,true);A.equal(r.stage.boss.mode,value);}G.dev(r,p,{action:'bossMark',value:{token:p.token}});G.dev(r,p,{action:'bossMark',value:{token:p.token,complete:false}});A.equal(r.stage.completed.length,0);});
test('full ordered six-player flow L1 → five caves → cargo entire route → boss → L5 → white → five sends → party',()=>{const {r,p,ps}=setup(1),tokens=ps.map(q=>q.token),momo=r.momoToken;[650,770,890].forEach((x,i)=>at(ps[i],x));advance(r,.025);at(ps[3],1200);G.interact(r,ps[3]);ps.forEach(q=>at(q,2760));advance(r,.025);A.ok(r.stage.cleared);G.interact(r,p);A.equal(r.stage.id,2);for(let i=0;i<20;i++)solve(r);ps.forEach(q=>at(q,5100));advance(r,.025);G.interact(r,p);A.equal(r.stage.id,3);
 // Fixture positions the route team at reachable physical switches, then three actual inputs push the full course.
 for(const k of D.cargo.switches){at(ps[3],k.x,k.y);G.interact(r,ps[3]);}ps.slice(3).forEach((q,i)=>at(q,4050+i*10,D.mountain(4050)));for(const [i,q]of ps.slice(0,3).entries()){at(q,200-i*10);q.input={right:true};}let regrouped=false;for(let n=0;n<9000&&!r.stage.cleared;n++){if(r.stage.finalCheckpoint&&!regrouped){ps.forEach((q,i)=>{const x=r.stage.cargo.x-80-i*3;at(q,x,D.mountain(x));q.input={right:true};});regrouped=true;}advance(r,.025);}A.ok(r.stage.cleared,'cargo full route delivered');A.ok(regrouped);G.interact(r,p);A.equal(r.stage.id,4);ps.forEach((q,i)=>{at(q,D.boss.buttons[i]);G.interact(r,q);});advance(r,2.2);A.ok(r.stage.cleared);G.interact(r,p);A.equal(r.stage.id,5);ps.forEach(q=>{at(q,5500,350);q.input={interact:true};});advance(r,3.05);A.equal(r.stage.id,'ending');A.equal(r.stage.phase,'white');advance(r,5.1);A.equal(L.privateClue(r,r.players.get(momo)).text,'啊……製作人做不下去了。\n沒想法了。');advance(r,11.6);ps.filter(q=>q.token!==momo).forEach(q=>A.ok(G.sendStar(r,q.token).ok));advance(r,11);A.equal(r.stage.id,'party');A.deepEqual([...r.players.keys()],tokens);A.equal(r.momoToken,momo);A.deepEqual(r.fragments,[1,2,3,4]);});

test('Cargo visual and prediction share bounded projection without changing authoritative state',()=>{const {r}=setup(3),c=r.stage.cargo;c.x=2800;c.vx=200;c.sampleAt=1;c.y=D.mountain(c.x)-c.r;const before=JSON.stringify(c),pose=D.cargoPose(c,1.1,r.stage.obstacles);A.ok(Math.abs(pose.x-2820)<.001);A.equal(JSON.stringify(c),before);A.equal(D.cargoPose(c,10).x,2840);c.x=2360;c.vx=200;c.sampleAt=1;A.equal(D.cargoPose(c,1.2,[true,false,false]).x,2365);});
