/* Build 0.4.1 mechanics; lifecycle, rooms and transport remain in engine/server. */
const crypto=require('crypto'),D=require('./public/geometry');
const shuffle=a=>{const b=a.slice();for(let i=b.length-1;i>0;i--){const j=crypto.randomInt(i+1);[b[i],b[j]]=[b[j],b[i]];}return b;};
const random=n=>crypto.randomInt(0,n);
const configs=[null,{length:4,display:2.5,limit:6},{length:4,display:2,limit:5},{length:5,display:1.9,limit:5},{length:6,display:2.8,limit:6},{length:8,display:3.5,limit:8}];
const rules=[{text:'星星比花朵多的那串是真的。',valid:a=>a.filter(x=>x===1).length>a.filter(x=>x===0).length},{text:'第二個與第四個符號相同的那串是真的。',valid:a=>a[1]===a[3]},{text:'第一個與最後一個符號不同的那串是真的。',valid:a=>a[0]!==a.at(-1)},{text:'第一顆星星在第一個月亮之前的那串是真的。',valid:a=>a.includes(1)&&a.includes(3)&&a.indexOf(1)<a.indexOf(3)},{text:'蘑菇數量為奇數的那串是真的。',valid:a=>a.filter(x=>x===2).length%2===1}];
function answerPair(n,rule){for(let i=0;i<10000;i++){const a=Array.from({length:n},()=>random(4));if(!rule.valid(a))continue;const b=a.slice(),j=random(n);b[j]=(b[j]+1+random(3))%4;if(!rule.valid(b))return [a,b];}throw Error('truth generation failed');}
function participants(r){return (r.stage.participants||[...r.players.keys()]).map(t=>r.players.get(t)).filter(Boolean);}
function inputCost(a){return a.slice(1).reduce((n,v,i)=>n+(v===a[i]?.34:Math.abs(v-a[i])===1?.36:1.15),0);}
function relayRound(r,G){const s=r.stage,a=shuffle(participants(r).map(p=>p.token));s.readers=a.slice(0,s.cave>=4?2:1);s.executors=a.filter(t=>!s.readers.includes(t)).slice(0,4);s.observers=a.filter(t=>!s.readers.includes(t)&&!s.executors.includes(t));s.leg=0;s.mode='waiting';s.entered=[];s.inputUntil=null;s.displayUntil=null;s.padContact=null;s.round=(s.round||0)+1;s.ruleIndex=random(rules.length);s.rule=s.cave>=4?rules[s.ruleIndex].text:'依照讀題者看到的順序踩地板。';s._legs=Array.from({length:4},()=>{const rule=rules[s.ruleIndex],cfg=configs[s.cave],pair=(()=>{let pair;do{pair=answerPair(cfg.length,rule);}while(inputCost(pair[0])>cfg.limit-.4);return pair;})(),[truth,fake]=pair;const reader=random(s.readers.length);return {truth,fake,reader,validation:[rule.valid(truth),rule.valid(fake)]};});s.cfg=configs[s.cave];for(const [i,p]of participants(r).entries()){p.flat=false;p.down=false;G.warp(p,D.caves[s.cave-1].start+i*38);p.checkpoint=D.caves[s.cave-1].start;}}
function failRelay(r,G){r.stage.failures=(r.stage.failures||0)+1;relayRound(r,G);G.event(r,'BOING！本洞重新分工與出題，前面洞穴保留。');}
function finishCave(r,G){const s=r.stage;s.caveCleared[s.cave]=true;if(s.cave<5){s.cave++;relayRound(r,G);}else{s.mode='complete';s._legs=[];G.event(r,'五座洞穴完成！六位一起到出口集合。');}}
function init(r,G){const s=r.stage;s.participants=[...r.players.keys()];
 if(s.id===2){Object.assign(s,{cave:1,caveCleared:[false,false,false,false,false,false],failures:0});relayRound(r,G);}
 if(s.id===3)Object.assign(s,{cargo:{x:280,y:365,r:D.hitboxes.cargo.radius,vx:0,vy:0,angle:0},obstacles:[false,false,false],plates:[],pushers:0,finalCheckpoint:false,delivered:false});
 if(s.id===4)Object.assign(s,{boss:{x:2000,y:420,mode:'crouch',start:r.time,until:r.time+1.5,attack:0},completed:[],bridgeOpen:false});
 if(s.id===5)Object.assign(s,{hold:0,arrivals:[],fallen:{},enemies:[{x:1530,base:1630,mode:'move'},{x:2980,base:3100,mode:'move'},{x:4460,base:4580,mode:'move'}]});
}
function flatten(r,p,G){if(p.down||p.flat||r.time<(p.invulnerableUntil||0))return;p.flat=true;p.flatAt=r.time;p.rescue=0;p.warp++;G.event(r,p.char==='小桃'?'系統：這個人等等還有用，不能死。':'啪！靠近並按住互動 0.5 秒救援！');}
function die(r,p,G){p.flat=false;p.down=true;p.respawnAt=r.time+.65;p.rescue=0;p.input={};p.warp++;}
function respawn(r,p,G){p.flat=false;p.down=false;p.invulnerableUntil=r.time+.1;const x=r.stage.id===4&&r.stage.completed.includes(p.token)?3550:p.checkpoint||120;G.warp(p,x,G.W.floor(r.stage,x));}
function survival(r,dt,G){for(const p of participants(r)){if(p.down&&p.respawnAt&&r.time>=p.respawnAt){respawn(r,p,G);delete p.respawnAt;}if(!p.flat)continue;const helper=participants(r).some(q=>q!==p&&(q.connected||q.bot)&&!q.down&&G.held(q)&&Math.abs(q.x-p.x)<75&&Math.abs(q.y-p.y)<65);p.rescue=helper?(p.rescue||0)+dt:0;if(p.rescue>=.5){p.flat=false;p.rescue=0;p.invulnerableUntil=r.time+.1;p.warp++;}else if(r.stage.id===5&&r.time-p.flatAt>3)die(r,p,G);}}
function action(r,p,data,G){const s=r.stage;if(s.id===2&&data.kind==='startLeg'){if(!s.readers.includes(p.token)||s.mode!=='waiting'||p.flat||p.down)return {ok:false,error:'等待讀題者手動開始下一棒。'};s.mode='display';s.displayUntil=r.time+s.cfg.display;s.startedBy=p.token;s.entered=[];s.padContact=null;return {ok:true};}
 if(s.id===4&&Math.abs(p.x-3600)<120&&!p.flat&&!p.down&&!s.bridgeOpen){if(!s.completed.includes(p.token))s.completed.push(p.token);return {ok:true};}return {ok:false,error:'請到自己的按鈕旁互動，或等待讀題者開始。'};}
function privateClue(r,p){const s=r.stage;if(s.id==='ending')return s.phase==='whiteText'?{text:p.token===r.momoToken?'啊……製作人做不下去了。\n沒想法了。':'系統好像漏掉了什麼。'}:null;if(s.id!==2)return null;const ri=s.readers.indexOf(p.token),leg=s._legs[s.leg];return {role:ri>=0?'reader':s.executors[s.leg]===p.token?'executor':s.executors.includes(p.token)?'waitingExecutor':'observer',sequence:s.mode==='display'&&r.time<s.displayUntil&&ri>=0&&leg?(ri===leg.reader?leg.truth:leg.fake):null};}
function cargoReset(r,G,final){const s=r.stage,c=s.cargo,x=final?D.cargo.finalBase:280;Object.assign(c,{x,y:D.mountain(x)-c.r,vx:0,vy:0,angle:0});if(!final){s.obstacles=[false,false,false];s.finalCheckpoint=false;}for(const [i,p]of participants(r).entries()){p.down=p.flat=false;p.checkpoint=final?4100:120;G.warp(p,(final?4020:120)+i*35,D.mountain((final?4020:120)+i*35));}G.event(r,final?'最後大坡失敗，回到坡腳再集合！':'貨物掉進主路線陷阱，本關重新開始！');}
function tick(r,dt,G){const s=r.stage,ps=participants(r),live=ps.filter(p=>(p.connected||p.bot)&&!p.down&&!p.flat);
 if(s.id===2){if(s.mode==='display'&&r.time>=s.displayUntil)s.mode='discussion';if(s.mode==='input'&&r.time>=s.inputUntil){failRelay(r,G);return;}if(['discussion','input'].includes(s.mode)){const p=r.players.get(s.executors[s.leg]),pads=D.caves[s.cave-1].pads;const idx=p&&!p.flat&&!p.down&&p.grounded&&Math.abs(p.y-420)<5?pads.findIndex(x=>Math.abs(p.x-x)<25):-1;if(idx<0)s.padContact=null;else if(s.padContact!==idx){s.padContact=idx;if(s.mode==='discussion'){s.mode='input';s.inputUntil=r.time+s.cfg.limit;}const leg=s._legs[s.leg];if(idx!==leg.truth[s.entered.length]){failRelay(r,G);return;}s.entered.push(idx);if(s.entered.length===s.cfg.length){s.leg++;s.mode='waiting';s.inputUntil=null;s.entered=[];if(s.leg===4)finishCave(r,G);}}}if(s.mode==='complete'&&ps.length===6&&ps.every(p=>(p.connected||p.bot)&&!p.down&&p.x>5000))G.clear(r,2);}
 if(s.id===3){const c=s.cargo;s.plates=D.cargo.obstacles.map(o=>o.plates.map(x=>live.some(p=>Math.abs(p.x-x)<27&&Math.abs(p.y-D.mountain(x))<15)));s.plates.forEach((a,i)=>{if(a.every(Boolean))s.obstacles[i]=true;});const n=s.simPushers??live.filter(p=>Math.abs(p.x-c.x)<115&&p.y>c.y-25&&p.x<c.x&&p.input.right).length;s.pushers=n;const final=c.x>=4200;s.warning=!final&&n>=4?'人太多了！貨物加速！':final&&n<5?'人不夠！貨物往下滾！':'';const target=final?[-150,-125,-100,-75,-45,8,72][n]:[c.x>400?-22:0,14,25,76,180,245,325][n];c.vx+=(target-c.vx)*Math.min(1,dt*2);const old=c.x;c.x=Math.max(100,c.x+c.vx*dt);c.y=D.mountain(c.x)-c.r;c.angle+=(c.x-old)/c.r;
 for(let i=0;i<3;i++){const o=D.cargo.obstacles[i];if(!s.obstacles[i]&&old<o.x&&c.x>=o.x){cargoReset(r,G,false);return;}}
 if(c.x>=4200&&!s.finalCheckpoint){s.finalCheckpoint=true;ps.forEach(p=>p.checkpoint=4100);G.event(r,'最後大坡：現在需要六個人一起推！');}if(s.finalCheckpoint&&c.x<4160){cargoReset(r,G,true);return;}
 if(!s.obstacles[2])for(const p of live)if(p.x>3150&&p.x<3350)p.kick=-160;
 for(const p of live)if(Math.abs(p.x-c.x)<c.r*.8&&p.y>c.y-10&&Math.abs(c.vx)>105)G.down(r,p,'被粉紅貨物壓成餅了！');
 if(c.x>5380&&!s.delivered){s.delivered=true;s.deliveredAt=r.time;c.vx=0;G.event(r,'箱子打開了……只有一朵蘑菇？');}if(s.delivered){c.x=5390;c.vx=0;if(r.time-s.deliveredAt>3){G.event(r,'NPC：辛苦了！');G.clear(r,3);}}}
 if(s.id===4){const b=s.boss;if(s.bridgeOpen){b.y+=320*dt;b.mode='fall';if(r.time-s.openAt>2)G.clear(r,4);return;}if(s.completed.length===6){s.bridgeOpen=true;s.openAt=r.time;G.event(r,'六個按鈕亮起，BOSS 腳下的橋打開了！');return;}
 const cycle=(r.time-s.at)%8;b.mode=cycle<1.4?'crouch':cycle<3.7?'leap':cycle<4.5?'slamWarning':cycle<4.85?'slam':cycle<6?'chargeWarning':cycle<6.9?'charge':'idle';b.y=['leap','slamWarning'].includes(b.mode)?190:420;b.x=b.mode==='charge'?2000+Math.sin((cycle-6)/.9*Math.PI)*290:2000;b.attack=Math.floor((r.time-s.at)/8);for(const p of live){const body=D.overlaps(D.bounds(p,'player'),D.bounds(b,'boss'));const slam=b.mode==='slam'&&Math.abs(p.x-b.x)<270&&p.y>390;if(body||slam)flatten(r,p,G);}}
 if(s.id===5){for(const p of live){for(const x of D.checkpoints)if(p.x>=x&&p.grounded&&p.y<600)p.checkpoint=Math.max(p.checkpoint,x);for(const b of D.racePlatforms(s,r.time))if(b.id.startsWith('fall')&&Math.abs(p.y-b.y)<3&&p.x>b.x&&p.x<b.x+b.w){if(!s.fallen[b.id]||r.time>s.fallen[b.id]+4)s.fallen[b.id]=r.time;}}
 for(const [i,m]of s.enemies.entries()){const phase=(r.time+i*1.7)%6;m.mode=phase<2?'move':phase<3?'warning':phase<4?'charge':phase<5?'jump':'slam';m.x=m.base+Math.sin(r.time*(m.mode==='charge'?2.5:.8)+i)*105;m.y=G.W.floor(s,m.x)-(m.mode==='jump'?95:0);for(const p of live)if(Math.abs(p.x-m.x)<(m.mode==='slam'?65:38)&&Math.abs(p.y-m.y)<40&&m.mode!=='warning')flatten(r,p,G);}
 s.arrivals=ps.filter(p=>(p.connected||p.bot)&&!p.down&&!p.flat&&p.x>5390&&p.y<400).map(p=>p.token);s.hold=ps.length===6&&s.arrivals.length===6&&ps.every(G.held)?s.hold+dt:0;if(s.hold>=3)G.enter(r,'ending');}
}
function dev(r,p,{action,value},G){const s=r.stage;switch(action){case 'relayInspect':if(s.id!==2)break;return {ok:true,inspect:{cave:s.cave,leg:s.leg+1,readers:s.readers,executors:s.executors,uniqueExecutors:new Set(s.executors).size===4,legs:s._legs,rule:s.rule}};case 'cave':if(s.id===2&&value>=1&&value<=5){s.cave=Number(value);s.caveCleared=s.caveCleared.map((_,i)=>i>0&&i<value);relayRound(r,G);return {ok:true};}break;case 'caveComplete':if(s.id===2){finishCave(r,G);return {ok:true};}break;case 'caveFail':if(s.id===2){failRelay(r,G);return {ok:true};}break;case 'cargoReset':if(s.id===3){cargoReset(r,G,false);return {ok:true};}break;case 'cargoCheckpoint':case 'finalSlope':if(s.id===3){s.finalCheckpoint=true;s.obstacles=[true,true,true];cargoReset(r,G,true);return {ok:true};}break;case 'pushers':if(s.id===3){s.simPushers=value===null?null:Math.max(0,Math.min(6,Number(value)));return {ok:true};}break;case 'flatten':{const q=r.players.get(value)||p;if([4,5].includes(s.id)){flatten(r,q,G);return {ok:true};}break;}case 'death':if(s.id===5){die(r,p,G);return {ok:true};}break;case 'bossAttack':if(s.id===4){const offsets={crouch:0,leap:1.5,slamWarning:3.8,slam:4.6,chargeWarning:5,charge:6.2};s.at=r.time-(offsets[value]??0);return {ok:true};}break;case 'bossMark':if(s.id===4){const t=value?.token||p.token;if(!r.players.has(t))break;s.completed=s.completed.filter(x=>x!==t);if(value?.complete!==false)s.completed.push(t);return {ok:true};}break;case 'bossAll':if(s.id===4){s.completed=participants(r).map(p=>p.token);return {ok:true};}break;case 'raceCheckpoint':if(s.id===5){const x=D.checkpoints[Number(value)]??120;p.checkpoint=x;respawn(r,p,G);return {ok:true};}break;case 'finalHold':if(s.id===5){participants(r).forEach((q,i)=>{q.flat=q.down=false;G.warp(q,5450+i*35,350);});return {ok:true};}break;case 'whitePreview':return {ok:true,inspect:{text:value==='momo'?'啊……製作人做不下去了。\n沒想法了。':'系統好像漏掉了什麼。',blankSeconds:5}};}
 return null;}
module.exports={inputCost,init,tick,action,privateClue,survival,flatten,die,respawn,dev,relayRound,answerPair,rules,configs,participants};
