/* Build 0.4.1 mechanics; lifecycle, rooms and transport remain in engine/server. */
const crypto=require('crypto'),D=require('./public/geometry');
const shuffle=a=>{const b=a.slice();for(let i=b.length-1;i>0;i--){const j=crypto.randomInt(i+1);[b[i],b[j]]=[b[j],b[i]];}return b;};
const random=n=>crypto.randomInt(0,n);
const configs=[null,{length:4,display:2.5,limit:6},{length:4,display:2,limit:5},{length:5,display:1.9,limit:5},{length:6,display:2.8,limit:6},{length:8,display:3.5,limit:8}];
const rules=[{text:'星星比花朵多的那串是真的。',valid:a=>a.filter(x=>x===1).length>a.filter(x=>x===0).length},{text:'第二個與第四個符號相同的那串是真的。',valid:a=>a[1]===a[3]},{text:'第一個與最後一個符號不同的那串是真的。',valid:a=>a[0]!==a.at(-1)},{text:'第一顆星星在第一個月亮之前的那串是真的。',valid:a=>a.includes(1)&&a.includes(3)&&a.indexOf(1)<a.indexOf(3)},{text:'蘑菇數量為奇數的那串是真的。',valid:a=>a.filter(x=>x===2).length%2===1}];
function answerPair(n,rule){for(let i=0;i<10000;i++){const a=Array.from({length:n},()=>random(4));if(!rule.valid(a))continue;const b=a.slice(),j=random(n);b[j]=(b[j]+1+random(3))%4;if(!rule.valid(b))return [a,b];}throw Error('truth generation failed');}
function participants(r){return (r.stage.participants||[...r.players.keys()]).map(t=>r.players.get(t)).filter(Boolean);}
function initCargoCoop(s){const tokens=s.participants.slice(0,6),pushTeam=tokens.slice(0,3),runnerTeam=tokens.slice(3,6),runnerAssignments={};D.cargo.coopSwitchIds.forEach((id,i)=>runnerAssignments[id]=runnerTeam[i]);Object.assign(s,{pushTeam,runnerTeam,runnerAssignments,bridgeOpeningAt:null,bridgeReadyAt:null,bridgeReady:false,bridgeFailure:false});}
function cargoCoreReady(s){return D.cargo.coopSwitchIds.every(id=>!!s.switches[id]);}
function refreshCargoRoute(s,time,G,r){if(cargoCoreReady(s)&&!s.bridgeReady&&s.bridgeOpeningAt==null){s.bridgeOpeningAt=time;s.bridgeReadyAt=time+D.cargo.bridgeOpenDelay;if(G&&r)G.event(r,'A / B / C 全部啟動！橋面展開中……先別把月亮推進斷橋！');}if(!s.bridgeReady&&s.bridgeReadyAt!=null&&time>=s.bridgeReadyAt){s.bridgeReady=true;if(G&&r)G.event(r,'喀！斷橋固定完成，可以推月亮通過了！');}s.obstacles=D.cargo.obstacles.map((o,i)=>i===0?!!s.bridgeReady:o.requires.every(id=>!!s.switches[id]));}
function resetCargoRoute(s){s.switches={};s.obstacles=[false,false,false];s.bridgeOpeningAt=null;s.bridgeReadyAt=null;s.bridgeReady=false;s.bridgeFailure=false;}

function inputCost(a){return a.slice(1).reduce((n,v,i)=>n+Math.abs(v-a[i])*75/210+.18,.18);}
function relayRound(r,G){const s=r.stage,a=shuffle(participants(r).map(p=>p.token));s.readers=a.slice(0,s.cave>=4?2:1);s.executors=a.filter(t=>!s.readers.includes(t)).slice(0,4);s.observers=a.filter(t=>!s.readers.includes(t)&&!s.executors.includes(t));s.leg=0;s.mode='waiting';s.entered=[];s.inputUntil=null;s.displayUntil=null;s.padContact=null;s.round=(s.round||0)+1;s.ruleIndex=random(rules.length);s.rule=s.cave>=4?rules[s.ruleIndex].text:'依照讀題者的順序，靠近符號按 E。';s._legs=Array.from({length:4},()=>{const rule=rules[s.ruleIndex],cfg=configs[s.cave],pair=(()=>{let pair;do{pair=answerPair(cfg.length,rule);}while(inputCost(pair[0])>cfg.limit-.4);return pair;})(),[truth,fake]=pair;const reader=random(s.readers.length);return {truth,fake,reader,validation:[rule.valid(truth),rule.valid(fake)]};});s.cfg=configs[s.cave];for(const [i,p]of participants(r).entries()){p.flat=false;p.down=false;G.warp(p,D.caves[s.cave-1].start+i*38);p.checkpoint=D.caves[s.cave-1].start;}}
function failRelay(r,G){r.stage.failures=(r.stage.failures||0)+1;relayRound(r,G);for(const p of participants(r)){p.vy=-360;p.grounded=false;}G.event(r,'BOING！本洞重新分工與出題，前面洞穴保留。');}
function finishCave(r,G){const s=r.stage;s.caveCleared[s.cave]=true;if(s.cave<5){s.cave++;relayRound(r,G);}else{s.mode='complete';s._legs=[];G.event(r,'五座洞穴完成！六位一起到出口集合。');}}
function createEnemies(time){const T=D.enemyTuning;return [
 {id:'patrol-1',type:'patrol',x:860,min:760,max:1010,dir:1,mode:'patrol',floor:420,speed:T.patrol.speed,start:time,sampleAt:time},
 {id:'hopper-1',type:'hopper',x:1580,min:1510,max:1740,dir:1,mode:'crouch',floor:370,jumpDuration:T.hopper.jumpDuration,jumpHeight:T.hopper.jumpHeight,start:time,until:time+T.hopper.crouch},
 {id:'patrol-2',type:'patrol',x:2180,min:2090,max:2390,dir:1,mode:'patrol',floor:370,speed:T.patrol.speed+4,start:time,sampleAt:time},
 {id:'hopper-2',type:'hopper',x:2310,min:2110,max:2400,dir:-1,mode:'crouch',floor:370,jumpDuration:T.hopper.jumpDuration,jumpHeight:T.hopper.jumpHeight,start:time+.1,until:time+T.hopper.crouch+.1},
 {id:'charger-1',type:'charger',x:3140,min:2990,max:3260,dir:-1,mode:'idle',floor:420,speed:T.charger.speed,start:time},
 {id:'patrol-3',type:'patrol',x:3700,min:3590,max:3890,dir:-1,mode:'patrol',floor:420,speed:T.patrol.speed+6,start:time,sampleAt:time},
 {id:'hopper-3',type:'hopper',x:4660,min:4450,max:4800,dir:1,mode:'crouch',floor:350,jumpDuration:T.hopper.jumpDuration,jumpHeight:T.hopper.jumpHeight+4,start:time+.2,until:time+T.hopper.crouch+.2},
 {id:'charger-2',type:'charger',x:4520,min:4420,max:4790,dir:-1,mode:'idle',floor:350,speed:T.charger.speed+20,start:time}
].map(m=>({...m,y:m.floor}));}
function init(r,G){const s=r.stage;s.polishVersion=s.id===3||s.id===5?2:1;s.participants=[...r.players.keys()];
 if(s.id===2){Object.assign(s,{cave:1,caveCleared:[false,false,false,false,false,false],failures:0});relayRound(r,G);}
 if(s.id===3){Object.assign(s,{cargo:{x:280,y:365,r:D.hitboxes.cargo.radius,vx:0,vy:0,angle:0},obstacles:[false,false,false],plates:[],switches:{},cargoCheckpoint:280,pushers:0,finalCheckpoint:false,delivered:false});initCargoCoop(s);G.event(r,'LV3 分工完成：前三位是推月亮組；後三位是前跑組，分別負責 A / B / C。');}
 if(s.id===4)Object.assign(s,{boss:{x:2000,y:420,fromX:2000,targetX:2000,dir:1,mode:'chargeWarning',start:r.time,until:r.time+.45,attack:0,next:'charge'},completed:[],bridgeOpen:false});
 if(s.id===5)Object.assign(s,{hold:0,arrivals:[],fallen:{},enemies:createEnemies(r.time)});
}
function flatten(r,p,G){if(p.down||p.flat||r.time<(p.invulnerableUntil||0))return;p.flat=true;p.flatAt=r.time;p.rescue=0;p.warp++;G.event(r,p.char==='小桃'?'系統：這個人等等還有用，不能死。':'啪！靠近並按住互動 0.5 秒救援！');}
function die(r,p,G){p.flat=false;p.down=true;p.respawnAt=r.time+.65;p.rescue=0;p.input={};p.warp++;}
function respawn(r,p,G){p.flat=false;p.down=false;p.invulnerableUntil=r.time+.5;const x=r.stage.id===4&&r.stage.completed.includes(p.token)?3550:p.checkpoint||120;G.warp(p,x,G.W.floor(r.stage,x));}
function survival(r,dt,G){for(const p of participants(r)){if(p.down&&p.respawnAt&&r.time>=p.respawnAt){respawn(r,p,G);delete p.respawnAt;}if(!p.flat)continue;const helper=participants(r).some(q=>q!==p&&(q.connected||q.bot)&&!q.down&&G.held(q)&&Math.abs(q.x-p.x)<75&&Math.abs(q.y-p.y)<65);p.rescue=helper?(p.rescue||0)+dt:0;if(p.rescue>=.5){p.flat=false;p.rescue=0;p.invulnerableUntil=r.time+.5;p.warp++;}else if(r.stage.id===3&&r.time-p.flatAt>=3){p.flat=false;p.invulnerableUntil=r.time+.5;p.warp++;}else if(r.stage.id===5&&r.time-p.flatAt>3)die(r,p,G);}}
function completeLeg(r,G){const s=r.stage;s.leg++;s.mode='waiting';s.inputUntil=null;s.entered=[];if(s.leg===4)finishCave(r,G);}
function action(r,p,data,G){const s=r.stage;if(p.down||p.flat)return {ok:false};
 if(s.id===2){const c=D.caves[s.cave-1],ri=s.readers.indexOf(p.token);
  if(s.mode==='waiting'&&ri>=0&&Math.abs(p.x-c.readers[ri])<48&&Math.abs(p.y-420)<65){s.mode='display';s.readAt=r.time;s.displayUntil=r.time+s.cfg.display;s.startedBy=p.token;s.entered=[];return {ok:true};}
  if(['discussion','input'].includes(s.mode)&&p.token===s.executors[s.leg]){const idx=c.pads.findIndex(x=>Math.abs(p.x-x)<31);if(idx<0||Math.abs(p.y-420)>60)return {ok:false};if(s.mode==='input'&&r.time>=s.inputUntil){failRelay(r,G);return {ok:false};}if(s.mode==='discussion'){s.mode='input';s.firstInputAt=r.time;s.inputUntil=r.time+s.cfg.limit;}if(idx!==s._legs[s.leg].truth[s.entered.length]){failRelay(r,G);return {ok:true};}s.entered.push(idx);if(s.entered.length===s.cfg.length)completeLeg(r,G);return {ok:true};}
  return {ok:false};}
 if(s.id===3){const found=D.cargo.switches.find(k=>!s.switches[k.id]&&Math.abs(p.x-k.x)<46&&Math.abs(p.y-k.y)<65);if(found){if(found.role){const owner=s.runnerAssignments?.[found.id];if(p.token!==owner){const ownerChar=r.players.get(owner)?.char||'指定前跑組夥伴';return {ok:false,error:`機關 ${found.role} 由 ${ownerChar} 負責。`};}}else if(found.id==='brake'&&!s.runnerTeam?.includes(p.token))return {ok:false,error:'緩衝機關由前跑組負責。'};s.switches[found.id]=true;refreshCargoRoute(s,r.time,G,r);G.event(r,'喀！'+found.label+(found.role?` 完成 (${found.role})`:''));return {ok:true};}return {ok:false};}
 if(s.id===4){const i=s.participants.indexOf(p.token),x=D.boss.buttons[i];if(p.x<D.boss.safeZoneStart)return {ok:false,error:'先越過破損橋跳台，到安全區才能啟動按鈕。'};if(Math.abs(p.x-x)<25&&Math.abs(p.y-420)<60&&!s.bridgeOpen){if(!s.completed.includes(p.token))s.completed.push(p.token);return {ok:true};}}
 return {ok:false};
}
function privateClue(r,p){const s=r.stage;if(s.id==='ending')return s.phase==='whiteText'?{text:p.token===r.momoToken?'啊……製作人做不下去了。\n沒想法了。':'系統好像漏掉了什麼。'}:null;if(s.id!==2)return null;const ri=s.readers.indexOf(p.token),leg=s._legs[s.leg];return {epoch:s.epoch,round:s.round,leg:s.leg,readerIndex:ri,readAt:s.readAt,until:s.displayUntil,role:ri>=0?'reader':s.executors[s.leg]===p.token?'executor':s.executors.includes(p.token)?'waitingExecutor':'observer',sequence:s.mode==='display'&&r.time<s.displayUntil&&ri>=0&&leg?(ri===leg.reader?leg.truth:leg.fake):null};}
function cargoReset(r,G,final,reason='route'){const s=r.stage,c=s.cargo,x=final?D.cargo.finalBase:(reason==='coopBridge'?280:(s.cargoCheckpoint>=D.cargo.mid?D.cargo.mid:280));Object.assign(c,{x,y:D.mountain(x)-c.r,vx:0,vy:0,angle:0,falling:false,fallReason:null});if(x===280){resetCargoRoute(s);s.finalCheckpoint=false;s.cargoCheckpoint=280;}for(const [i,p]of participants(r).entries()){p.down=p.flat=false;p.respawnAt=null;p.checkpoint=final?4100:x===280?120:2500;const px=p.checkpoint+i*20;G.warp(p,px,D.mountain(px));}G.event(r,final?'最後大坡失敗，回到坡腳再集合！':x===280?'月亮掉落，回到起點再試一次！':'月亮回到中途旗子，前面的機關保留。');}
function beginBoss(r,mode,dir,targetX){const b=r.stage.boss,durations={chargeWarning:.45,charge:.62,recovery:.65,crouch:.32,leap:1.25,slam:.2,stompWarning:.3,stomp:.18};Object.assign(b,{mode,start:r.time,until:r.time+(durations[mode]||.65),fromX:b.x,y:420});if(dir)b.dir=dir;if(mode==='crouch'){const desired=targetX??b.x;b.targetX=Math.max(D.boss.bounds[0],Math.min(D.boss.bounds[1],Math.max(b.x-D.boss.attack.leapTrack,Math.min(b.x+D.boss.attack.leapTrack,desired))));}if(mode==='chargeWarning'||mode==='crouch'||mode==='stompWarning')b.attack++;}
function tickBoss(r,dt,live,G){const s=r.stage,b=s.boss;if(s.bridgeOpen){b.y+=320*dt;b.mode='fall';if(r.time-s.openAt>2)G.clear(r,4);return;}if(s.completed.length===6){s.bridgeOpen=true;s.openAt=r.time;G.event(r,'六個按鈕亮起，BOSS 腳下的橋打開了！');return;}
 const threats=live.filter(p=>p.x>D.boss.zone[0]-220&&p.x<D.boss.zone[1]+220);
 if(r.time>=b.until){const m=b.mode;if(m==='chargeWarning'){b.next='crouch';beginBoss(r,'charge');}else if(m==='crouch')beginBoss(r,'leap');else if(m==='leap')beginBoss(r,'slam');else if(m==='stompWarning')beginBoss(r,'stomp');else if(['charge','slam','stomp'].includes(m)){b.next=m==='charge'?'crouch':m==='slam'?'stompWarning':'chargeWarning';beginBoss(r,'recovery');}else{const q=threats.slice().sort((a,c)=>Math.abs(a.x-b.x)-Math.abs(c.x-b.x))[0];let dir=q?Math.sign(q.x-b.x)||1:b.dir;if(b.x<1830)dir=1;if(b.x>2190)dir=-1;let mode=b.next||((q&&Math.abs(q.x-b.x)<105)?'stompWarning':'chargeWarning');if(!['crouch','stompWarning','chargeWarning'].includes(mode))mode='chargeWarning';b.next=null;beginBoss(r,mode,dir,q?.x);}}
 Object.assign(b,D.bossPose(b,r.time));for(const p of live){const body=D.overlaps(D.bounds(p,'player'),D.bounds(b,'boss'));const shock=['slam','stomp'].includes(b.mode)&&Math.abs(p.x-b.x)<(b.mode==='slam'?D.boss.attack.slamRadius:D.boss.attack.stompRadius)&&p.y>396;if(body||shock){flatten(r,p,G);if(p.flat)p.kick=(Math.sign(p.x-b.x)||1)*82;}}
 for(const p of live)if(p.x>D.boss.zone[1]+10&&p.x<D.boss.safeZoneStart)p.checkpoint=Math.max(p.checkpoint,D.boss.escapeCheckpoint);
}
function tickEnemies(r,dt,live,G){const T=D.enemyTuning;for(const m of r.stage.enemies){
 if(m.type==='patrol'){if(m.mode==='patrol'){m.x+=m.dir*(m.speed||T.patrol.speed)*dt;if(m.x>=m.max||m.x<=m.min){m.x=Math.max(m.min,Math.min(m.max,m.x));m.mode='turn';m.start=r.time;m.until=r.time+T.patrol.turnDelay;}}else if(r.time>=m.until){m.dir*=-1;m.mode='patrol';m.start=r.time;}m.sampleAt=r.time;}
 else if(m.type==='hopper'&&r.time>=m.until){if(m.mode==='crouch'){const q=live.filter(p=>Math.abs(p.y-m.floor)<90&&Math.abs(p.x-m.x)<270).sort((a,b)=>Math.abs(a.x-m.x)-Math.abs(b.x-m.x))[0],maxTrack=T.hopper.track,desired=q?q.x:m.x+m.dir*85,dx=Math.max(-maxTrack,Math.min(maxTrack,desired-m.x));m.jumpFromX=m.x;m.jumpToX=Math.max(m.min,Math.min(m.max,m.x+dx));m.dir=Math.sign(m.jumpToX-m.x)||m.dir;m.mode='jump';m.start=r.time;m.until=r.time+(m.jumpDuration||T.hopper.jumpDuration);}else if(m.mode==='jump'){m.mode='rest';m.start=r.time;m.until=r.time+T.hopper.rest;}else{m.mode='crouch';m.start=r.time;m.until=r.time+T.hopper.crouch;}}
 else if(m.type==='charger'){if(m.mode==='idle'){const q=live.filter(p=>Math.abs(p.x-m.x)<T.charger.detect&&Math.abs(p.y-m.floor)<72).sort((a,b)=>Math.abs(a.x-m.x)-Math.abs(b.x-m.x))[0];if(q){m.dir=Math.sign(q.x-m.x)||m.dir||1;m.mode='warning';m.start=r.time;m.until=r.time+T.charger.warning;m.targetToken=q.token;}}else if(r.time>=m.until){if(m.mode==='warning'){m.mode='charge';m.start=r.time;m.fromX=m.x;m.until=r.time+T.charger.chargeDuration;}else if(m.mode==='charge'){m.mode='recovery';m.start=r.time;m.until=r.time+T.charger.recovery;}else{m.mode='idle';m.start=r.time;m.targetToken=null;}}}
 const pose=D.enemyPose(m,r.time);if(m.type!=='patrol')m.x=pose.x;m.y=pose.y;for(const p of live)if(D.overlaps(D.bounds(p,'player'),D.bounds(m,'enemy')))flatten(r,p,G);
 }}
function tick(r,dt,G){const s=r.stage,ps=participants(r),live=ps.filter(p=>(p.connected||p.bot)&&!p.down&&!p.flat);
 if(s.id===2){if(s.mode==='display'&&r.time>=s.displayUntil)s.mode='discussion';if(s.mode==='input'&&r.time>=s.inputUntil){failRelay(r,G);return;}if(s.mode==='complete'&&ps.length===6&&ps.every(p=>(p.connected||p.bot)&&!p.down&&p.x>5000))G.clear(r,2);}
 if(s.id===3){const c=s.cargo;if(c.falling){c.sampleAt=r.time;c.vy+=1050*dt;c.y+=c.vy*dt;if(c.y>750)cargoReset(r,G,s.finalCheckpoint,c.fallReason||'route');return;}
  refreshCargoRoute(s,r.time,G,r);const final=s.finalCheckpoint||c.x>=4200,eligible=final?live:live.filter(p=>s.pushTeam?.includes(p.token));const n=s.simPushers??eligible.filter(p=>Math.abs(p.x-c.x)<120&&p.y>c.y-25&&p.x<c.x&&p.input.right).length;s.pushers=n;s.pusherGoal=final?6:3;s.warning=!final&&n<3?'推月亮組需要 3 人一起推！':!final&&!s.bridgeReady&&cargoCoreReady(s)?'橋面展開中，先穩住月亮！':final&&n<5?'人不夠！月亮往下滾！':'';
  let target=final?[-150,-125,-100,-75,-45,8,72][n]:[0,14,26,85,185,255,335][n]+D.slope(c.x)*420*(D.slope(c.x)<0&&n?.3:1);if(s.switches.brake&&c.x>3350&&c.x<3690)target=Math.min(72,target);
  c.vx+=(target-c.vx)*Math.min(1,dt*2);const old=c.x;c.x=Math.max(100,c.x+c.vx*dt);if(!s.obstacles[1]&&old<2420-c.r&&c.x>=2420-c.r){c.x=2420-c.r;c.vx=0;}c.y=D.mountain(c.x)-c.r;c.angle+=(c.x-old)/c.r;c.sampleAt=r.time;
  const failedBridge=D.cargo.obstacles.findIndex((o,i)=>o.kind==='bridge'&&!s.obstacles[i]&&c.x>o.x+c.r*.3&&c.x<o.end);if(failedBridge>=0){c.falling=true;c.vy=0;c.fallReason=failedBridge===0&&!s.bridgeReady?'coopBridge':'route';if(c.fallReason==='coopBridge'){s.bridgeFailure=true;G.event(r,'危險！A / B / C 或橋面展開還沒完成，大月亮掉進斷橋！');}return;}
  if(c.x>=2500&&s.cargoCheckpoint<2500){s.cargoCheckpoint=2500;G.event(r,'中途檢查點！前方下坡，先開啟接應橋。');}for(const p of live){if(p.x>=2500&&p.grounded)p.checkpoint=Math.max(p.checkpoint,2500);if(p.x>=4100&&p.grounded)p.checkpoint=4100;}
  if(c.x>=4200&&!s.finalCheckpoint){s.finalCheckpoint=true;s.cargoCheckpoint=4200;ps.forEach(p=>p.checkpoint=4100);G.event(r,'最後大坡：現在需要六個人一起推！');}if(s.finalCheckpoint&&c.x<4160){cargoReset(r,G,true);return;}
  for(const p of live)if(Math.abs(p.x-c.x)<c.r*.8&&p.y>c.y-10&&Math.abs(c.vx)>110){flatten(r,p,G);p.kick=Math.sign(c.vx)*120;}
  if(c.x>5380&&!s.delivered){s.delivered=true;s.deliveredAt=r.time;c.vx=0;G.event(r,'箱子打開了……只有一朵蘑菇？');}if(s.delivered){c.x=5390;c.vx=0;if(r.time-s.deliveredAt>3){G.event(r,'NPC：辛苦了！');G.clear(r,3);}}}
 if(s.id===4)tickBoss(r,dt,live,G);
 if(s.id===5){for(const p of live){for(const x of D.checkpoints)if(p.x>=x&&p.grounded&&p.y<600)p.checkpoint=Math.max(p.checkpoint,x);for(const b of D.racePlatforms(s,r.time))if(b.id.startsWith('fall')&&Math.abs(p.y-b.y)<3&&p.x>b.x&&p.x<b.x+b.w){if(!s.fallen[b.id]||r.time>s.fallen[b.id]+4)s.fallen[b.id]=r.time;}}tickEnemies(r,dt,live,G);s.arrivals=ps.filter(p=>(p.connected||p.bot)&&!p.down&&!p.flat&&p.x>5390&&p.y<400).map(p=>p.token);s.hold=ps.length===6&&s.arrivals.length===6&&ps.every(G.held)?s.hold+dt:0;if(s.hold>=3)G.enter(r,'ending');}
}
function dev(r,p,{action:command,value},G){const s=r.stage;switch(command){case 'legStart':if(s.id===2&&s.mode==='waiting'){const q=r.players.get(s.readers[0]);G.warp(q,D.caves[s.cave-1].readers[0]);return action(r,q,{},G);}break;case 'legComplete':if(s.id===2&&s.mode!=='complete'){completeLeg(r,G);return {ok:true};}break;case 'relayInspect':if(s.id!==2)break;return {ok:true,inspect:{cave:s.cave,leg:s.leg+1,readers:s.readers,executors:s.executors,uniqueExecutors:new Set(s.executors).size===4,legs:s._legs,rule:s.rule}};case 'cave':if(s.id===2&&value>=1&&value<=5){s.cave=Number(value);s.caveCleared=s.caveCleared.map((_,i)=>i>0&&i<value);relayRound(r,G);return {ok:true};}break;case 'caveComplete':if(s.id===2){finishCave(r,G);return {ok:true};}break;case 'caveFail':if(s.id===2){failRelay(r,G);return {ok:true};}break;case 'cargoReset':if(s.id===3){s.cargoCheckpoint=280;cargoReset(r,G,false);return {ok:true};}break;case 'cargoCheckpoint':case 'downhill':if(s.id===3){s.cargoCheckpoint=2500;s.finalCheckpoint=false;s.switches={bridge:true,gateA:true,gateB:true};s.bridgeReady=true;s.bridgeOpeningAt=r.time-D.cargo.bridgeOpenDelay;s.bridgeReadyAt=r.time;s.obstacles=[true,true,false];cargoReset(r,G,false);if(command==='downhill'){s.cargo.x=2750;s.cargo.y=D.mountain(2750)-55;}return {ok:true};}break;case 'finalSlope':if(s.id===3){s.finalCheckpoint=true;s.switches={bridge:true,gateA:true,gateB:true,brake:true};s.bridgeReady=true;s.bridgeOpeningAt=r.time-D.cargo.bridgeOpenDelay;s.bridgeReadyAt=r.time;s.obstacles=[true,true,true];cargoReset(r,G,true);return {ok:true};}break;case 'pushers':if(s.id===3){s.simPushers=value===null?null:Math.max(0,Math.min(6,Number(value)));return {ok:true};}break;case 'flatten':{const q=r.players.get(value)||p;if([3,4,5].includes(s.id)){flatten(r,q,G);return {ok:true};}break;}case 'death':if(s.id===5){die(r,p,G);return {ok:true};}break;case 'bossAttack':if(s.id===4){beginBoss(r,['chargeWarning','charge','crouch','leap','slam','stompWarning','stomp','recovery'].includes(value)?value:value==='slamWarning'?'crouch':'recovery',1);return {ok:true};}break;case 'bossMark':if(s.id===4){const t=value?.token||p.token;if(!r.players.has(t))break;s.completed=s.completed.filter(x=>x!==t);if(value?.complete!==false)s.completed.push(t);return {ok:true};}break;case 'bossAll':if(s.id===4){s.completed=participants(r).map(p=>p.token);return {ok:true};}break;case 'raceCheckpoint':if(s.id===5){const x=D.checkpoints[Number(value)]??120;p.checkpoint=x;respawn(r,p,G);return {ok:true};}break;case 'finalHold':if(s.id===5){participants(r).forEach((q,i)=>{q.flat=q.down=false;G.warp(q,5450+i*35,350);});return {ok:true};}break;case 'whitePreview':return {ok:true,inspect:{text:value==='momo'?'啊……製作人做不下去了。\n沒想法了。':'系統好像漏掉了什麼。',blankSeconds:5}};}
 return null;}
module.exports={inputCost,init,tick,action,privateClue,survival,flatten,die,respawn,dev,relayRound,answerPair,rules,configs,participants,beginBoss,cargoReset,createEnemies,initCargoCoop,cargoCoreReady,refreshCargoRoute,tickEnemies};
